#############################################################################
# Makefile for building: JOINUS-V2.0.app/Contents/MacOS/JOINUS-V2.0
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  SIMGUI.pro
# Template: app
# Command: /Users/pascalf/Qt/5.12.4/clang_64/bin/qmake -o Makefile SIMGUI.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../../Qt/5.12.4/clang_64/mkspecs/macx-clang -F/Users/pascalf/Qt/5.12.4/clang_64/lib
QMAKE         = /Users/pascalf/Qt/5.12.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/pascalf/Qt/5.12.4/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/pascalf/Qt/5.12.4/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = JOINUS-V2.01.0.0
DISTDIR = /Users/pascalf/Desktop/JOINUS/SIMGUI/.tmp/JOINUS-V2.01.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/pascalf/Qt/5.12.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/pascalf/Qt/5.12.4/clang_64/lib -framework QtPrintSupport -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		plotwindow.cpp \
		dialogplot.cpp \
		myglobalvars.cpp \
		calcvals.cpp \
		simulateall.cpp \
		jsimsyntax.cpp \
		autooptim.cpp qrc_simguiresources.cpp \
		moc_mainwindow.cpp \
		moc_qcustomplot.cpp \
		moc_plotwindow.cpp \
		moc_dialogplot.cpp \
		moc_autooptim.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qcustomplot.o \
		plotwindow.o \
		dialogplot.o \
		myglobalvars.o \
		calcvals.o \
		simulateall.o \
		jsimsyntax.o \
		autooptim.o \
		qrc_simguiresources.o \
		moc_mainwindow.o \
		moc_qcustomplot.o \
		moc_plotwindow.o \
		moc_dialogplot.o \
		moc_autooptim.o
DIST          = ../../../Qt/5.12.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qtquickcompiler.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/lex.prf \
		SIMGUI.pro mainwindow.h \
		qcustomplot.h \
		plotwindow.h \
		dialogplot.h \
		myglobalvars.h \
		calcvals.h \
		simulateall.h \
		jsimsyntax.h \
		autooptim.h main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		plotwindow.cpp \
		dialogplot.cpp \
		myglobalvars.cpp \
		calcvals.cpp \
		simulateall.cpp \
		jsimsyntax.cpp \
		autooptim.cpp
QMAKE_TARGET  = JOINUS-V2.0
DESTDIR       = 
TARGET        = JOINUS-V2.0.app/Contents/MacOS/JOINUS-V2.0

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14.6
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/pascalf/Desktop/JOINUS/SIMGUI/SIMGUI.pro


include /Users/pascalf/Qt/5.12.4/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

JOINUS-V2.0.app/Contents/MacOS/JOINUS-V2.0: ui_mainwindow.h ui_plotwindow.h ui_dialogplot.h ui_dialogsetparam.h ui_autooptim.h $(OBJECTS)  
	@test -d JOINUS-V2.0.app/Contents/MacOS/ || mkdir -p JOINUS-V2.0.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SIMGUI.pro ../../../Qt/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.12.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.12.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qtquickcompiler.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/mac.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.12.4/clang_64/mkspecs/features/lex.prf \
		SIMGUI.pro \
		simguiresources.qrc \
		../../../Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile SIMGUI.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler
../../../Qt/5.12.4/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.12.4/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.12.4/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.12.4/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.12.4/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.12.4/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_studio3d_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.12.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.12.4/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.12.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.12.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.12.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/toolchain.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/qtquickcompiler.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/mac.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/file_copies.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.12.4/clang_64/mkspecs/features/lex.prf:
SIMGUI.pro:
simguiresources.qrc:
../../../Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../Qt/5.12.4/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt/5.12.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SIMGUI.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qtquickcompiler

qmake_all: FORCE

JOINUS-V2.0.app/Contents/PkgInfo: 
	@test -d JOINUS-V2.0.app/Contents || mkdir -p JOINUS-V2.0.app/Contents
	@$(DEL_FILE) JOINUS-V2.0.app/Contents/PkgInfo
	@echo "APPL????" > JOINUS-V2.0.app/Contents/PkgInfo
JOINUS-V2.0.app/Contents/Resources/empty.lproj: 
	@test -d JOINUS-V2.0.app/Contents/Resources || mkdir -p JOINUS-V2.0.app/Contents/Resources
	@touch JOINUS-V2.0.app/Contents/Resources/empty.lproj
	
JOINUS-V2.0.app/Contents/Info.plist: 
	@test -d JOINUS-V2.0.app/Contents || mkdir -p JOINUS-V2.0.app/Contents
	@$(DEL_FILE) JOINUS-V2.0.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.JOINUS-V2.0,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.JOINUS-V2.0,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,JOINUS-V2.0,g" -e "s,@LIBRARY@,JOINUS-V2.0,g" -e "s,\$${EXECUTABLE_NAME},JOINUS-V2.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../../Qt/5.12.4/clang_64/mkspecs/macx-clang/Info.plist.app >JOINUS-V2.0.app/Contents/Info.plist

all: Makefile \
		JOINUS-V2.0.app/Contents/PkgInfo \
		JOINUS-V2.0.app/Contents/Resources/empty.lproj \
		JOINUS-V2.0.app/Contents/Info.plist JOINUS-V2.0.app/Contents/MacOS/JOINUS-V2.0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents simguiresources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.12.4/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h qcustomplot.h plotwindow.h dialogplot.h myglobalvars.h calcvals.h simulateall.h jsimsyntax.h autooptim.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp qcustomplot.cpp plotwindow.cpp dialogplot.cpp myglobalvars.cpp calcvals.cpp simulateall.cpp jsimsyntax.cpp autooptim.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui plotwindow.ui dialogplot.ui dialogsetparam.ui autooptim.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r JOINUS-V2.0.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_simguiresources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_simguiresources.cpp
qrc_simguiresources.cpp: simguiresources.qrc \
		../../../Qt/5.12.4/clang_64/bin/rcc \
		Help/Margin.png \
		Help/Yield.png \
		Help/JOINUS-manual-in-a-nutshell-v2.0.pdf \
		Help/Optimizer.PNG \
		Help/JSIM-manual-v12.0.pdf \
		josim.lib \
		Data/si.inp \
		Add-ons/Help/about_parameters_file.html \
		Add-ons/Help/about_program.html \
		Add-ons/Help/about_Idc.html \
		Add-ons/Help/index.html
	/Users/pascalf/Qt/5.12.4/clang_64/bin/rcc -name simguiresources simguiresources.qrc -o qrc_simguiresources.cpp

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.12.4/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.12.4/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qcustomplot.cpp moc_plotwindow.cpp moc_dialogplot.cpp moc_autooptim.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qcustomplot.cpp moc_plotwindow.cpp moc_dialogplot.cpp moc_autooptim.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		autooptim.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		moc_predefs.h \
		../../../Qt/5.12.4/clang_64/bin/moc
	/Users/pascalf/Qt/5.12.4/clang_64/bin/moc $(DEFINES) --include /Users/pascalf/Desktop/JOINUS/SIMGUI/moc_predefs.h -I/Users/pascalf/Qt/5.12.4/clang_64/mkspecs/macx-clang -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/pascalf/Qt/5.12.4/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		moc_predefs.h \
		../../../Qt/5.12.4/clang_64/bin/moc
	/Users/pascalf/Qt/5.12.4/clang_64/bin/moc $(DEFINES) --include /Users/pascalf/Desktop/JOINUS/SIMGUI/moc_predefs.h -I/Users/pascalf/Qt/5.12.4/clang_64/mkspecs/macx-clang -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/pascalf/Qt/5.12.4/clang_64/lib qcustomplot.h -o moc_qcustomplot.cpp

moc_plotwindow.cpp: plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		moc_predefs.h \
		../../../Qt/5.12.4/clang_64/bin/moc
	/Users/pascalf/Qt/5.12.4/clang_64/bin/moc $(DEFINES) --include /Users/pascalf/Desktop/JOINUS/SIMGUI/moc_predefs.h -I/Users/pascalf/Qt/5.12.4/clang_64/mkspecs/macx-clang -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/pascalf/Qt/5.12.4/clang_64/lib plotwindow.h -o moc_plotwindow.cpp

moc_dialogplot.cpp: dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		moc_predefs.h \
		../../../Qt/5.12.4/clang_64/bin/moc
	/Users/pascalf/Qt/5.12.4/clang_64/bin/moc $(DEFINES) --include /Users/pascalf/Desktop/JOINUS/SIMGUI/moc_predefs.h -I/Users/pascalf/Qt/5.12.4/clang_64/mkspecs/macx-clang -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/pascalf/Qt/5.12.4/clang_64/lib dialogplot.h -o moc_dialogplot.cpp

moc_autooptim.cpp: autooptim.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		moc_predefs.h \
		../../../Qt/5.12.4/clang_64/bin/moc
	/Users/pascalf/Qt/5.12.4/clang_64/bin/moc $(DEFINES) --include /Users/pascalf/Desktop/JOINUS/SIMGUI/moc_predefs.h -I/Users/pascalf/Qt/5.12.4/clang_64/mkspecs/macx-clang -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Desktop/JOINUS/SIMGUI -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtGui.framework/Headers -I/Users/pascalf/Qt/5.12.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -F/Users/pascalf/Qt/5.12.4/clang_64/lib autooptim.h -o moc_autooptim.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_plotwindow.h ui_dialogplot.h ui_dialogsetparam.h ui_autooptim.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_plotwindow.h ui_dialogplot.h ui_dialogsetparam.h ui_autooptim.h
ui_mainwindow.h: mainwindow.ui \
		../../../Qt/5.12.4/clang_64/bin/uic
	/Users/pascalf/Qt/5.12.4/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_plotwindow.h: plotwindow.ui \
		../../../Qt/5.12.4/clang_64/bin/uic \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric
	/Users/pascalf/Qt/5.12.4/clang_64/bin/uic plotwindow.ui -o ui_plotwindow.h

ui_dialogplot.h: dialogplot.ui \
		../../../Qt/5.12.4/clang_64/bin/uic
	/Users/pascalf/Qt/5.12.4/clang_64/bin/uic dialogplot.ui -o ui_dialogplot.h

ui_dialogsetparam.h: dialogsetparam.ui \
		../../../Qt/5.12.4/clang_64/bin/uic
	/Users/pascalf/Qt/5.12.4/clang_64/bin/uic dialogsetparam.ui -o ui_dialogsetparam.h

ui_autooptim.h: autooptim.ui \
		../../../Qt/5.12.4/clang_64/bin/uic
	/Users/pascalf/Qt/5.12.4/clang_64/bin/uic autooptim.ui -o ui_autooptim.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		autooptim.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		autooptim.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		ui_mainwindow.h \
		myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		calcvals.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QString \
		simulateall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

plotwindow.o: plotwindow.cpp plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		ui_plotwindow.h \
		myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		autooptim.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		readoutdata.cpp \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QTextStream \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QLineEdit \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qlineedit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotwindow.o plotwindow.cpp

dialogplot.o: dialogplot.cpp dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		ui_dialogplot.h \
		myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogplot.o dialogplot.cpp

myglobalvars.o: myglobalvars.cpp myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myglobalvars.o myglobalvars.cpp

calcvals.o: calcvals.cpp calcvals.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtMath \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegExp \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregexp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calcvals.o calcvals.cpp

simulateall.o: simulateall.cpp simulateall.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		myglobalvars.h \
		mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		autooptim.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		calcvals.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegExp \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QProcess \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QVector \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qvector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulateall.o simulateall.cpp

jsimsyntax.o: jsimsyntax.cpp jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QTextCharFormat \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qcolor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsimsyntax.o jsimsyntax.cpp

autooptim.o: autooptim.cpp autooptim.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ui_autooptim.h \
		myglobalvars.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		simulateall.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QString \
		calcvals.h \
		mainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QSysInfo \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		dialogplot.h \
		plotwindow.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../../Qt/5.12.4/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		qcustomplot.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QtNumeric \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		jsimsyntax.h \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/QSyntaxHighlighter \
		../../../Qt/5.12.4/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/QRegularExpression \
		../../../Qt/5.12.4/clang_64/lib/QtCore.framework/Headers/qregularexpression.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autooptim.o autooptim.cpp

qrc_simguiresources.o: qrc_simguiresources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_simguiresources.o qrc_simguiresources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_plotwindow.o: moc_plotwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotwindow.o moc_plotwindow.cpp

moc_dialogplot.o: moc_dialogplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogplot.o moc_dialogplot.cpp

moc_autooptim.o: moc_autooptim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autooptim.o moc_autooptim.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

